# Generated by Django 4.1.3 on 2024-08-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_user_name_delete_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_name',
            new_name='User',
        ),
    ]
